### ISSUE TITLE
Mermaid Graphs cut off text at the end

### ISSUE THREAD

**Issue by dm1090** [gt6796c/mermaid-tw5#14]
The Mermaid graph is not rendering last letter of any label. 

![image](https://user-images.githubusercontent.com/35905135/71549113-e85f7c00-296c-11ea-9969-4fef792cebf3.png)

We can try to resolve this by add extra characters to the end. The problem is part of those extra characters are visible.

**Comment by sobjornstad** [comment]
This is happening for me, too -- but oddly it looks fine when previewing a tiddler.

**Comment by sobjornstad** [comment]
Found the culprit: the `tc-tiddler-body` CSS class increases the font size to 15px from 14px, while the plugin appears to be rendering expecting the font size to be 14px (as it is when previewing, since the `tc-tiddler-body` class is not above it in the DOM).

Quick workaround, add the following to a tiddler tagged `$:/tags/Stylesheet`:

```css
/* Override bugfix for plugin: https://github.com/gt6796c/mermaid-tw5/issues/14 */

.tc-tiddler-body div > svg {
  font-size: 14px;
}
```
